"""empty message

Revision ID: 16238f11bfbb
Revises: 3d2d8236cc4d
Create Date: 2020-12-25 18:40:13.664659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16238f11bfbb'
down_revision = '3d2d8236cc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('boards')
    # ### end Alembic commands ###
