"""empty message

Revision ID: bc75deef32c0
Revises: 16238f11bfbb
Create Date: 2020-12-27 23:40:25.385189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc75deef32c0'
down_revision = '16238f11bfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookitem', sa.Column('condition', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookitem', 'condition')
    op.drop_table('book_condition')
    # ### end Alembic commands ###
