"""empty message

Revision ID: fb2100c6b8ba
Revises: 
Create Date: 2020-12-20 21:02:04.813807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2100c6b8ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('examboard', sa.String(length=30), nullable=True),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('branch',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('contact_person', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('notification_template',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=60), nullable=True),
    sa.Column('template_text', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('bookitem',
    sa.Column('book_item_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('promise_date', sa.Date(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('book_item_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('book_item_id', sa.Integer(), nullable=True),
    sa.Column('transaction_account', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('award_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_item_id'], ['bookitem.book_item_id'], ),
    sa.ForeignKeyConstraint(['transaction_account'], ['user.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('bookitem')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('notification_template')
    op.drop_table('branch')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
